### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by KPCOFGS** [JacobCorey94/AMD-TRNG-Testing#1]
I think this repository is missing a LICENSE file

**Comment by JacobCorey94** [comment]
Never gave it a thought. Probably not a bad idea to have one, though. I'll get around to it, but feel free to just use the code, it's fine. All I've done since I've graduated is upload some more test results on the Intel testing side of things. I don't think any of the actual C++ code will ever be updated, unless something serious occurs.

**Comment by JacobCorey94** [comment]
Went ahead and added GPL 3.0
